version: '3.8'

services:
  web:
    build: .
    command: ./run_daphne_with_reload.sh  # Use the script for auto-reload
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"


