# Generated by Django 5.1.1 on 2024-09-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserBillingInfoModel',
        ),
    ]
