# Generated by Django 5.1.1 on 2024-10-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='website_link',
        ),
    ]
