# Generated by Django 5.1.1 on 2024-10-01 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('voucher_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=10)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('minimum_spending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_spending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birthday_members_only', models.BooleanField(default=False)),
                ('standalone_voucher', models.BooleanField(default=False)),
                ('apply_on_all_items', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='vouchers.voucher')),
            ],
        ),
    ]
