# Generated by Django 5.1.1 on 2024-10-02 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='apply_on_all_items',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='standalone_voucher',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(default='popopopo', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
