# Generated by Django 5.1.1 on 2024-10-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_remove_voucher_apply_on_all_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='maximum_spending',
        ),
        migrations.AddField(
            model_name='voucher',
            name='maximum_usability_of_voucher',
            field=models.IntegerField(default=5, verbose_name='Maximum Usability of Voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
