# Generated by Django 5.1.1 on 2024-10-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_remove_voucher_maximum_spending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheravailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='voucheravailability',
            name='start_time',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('voucher_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='vouchers.voucheravailability')),
            ],
        ),
    ]
